matrix:
  include:
    - os: linux
      dist: trusty
      env:
          N=VALGRIND
          LAST_CMD=./tests/valgrind_run.sh
    - os: linux
      dist: trusty
      env:
          N=GCOV
          CMAKE_ARG="-DGCOV=ON"
          LAST_CMD="make coverage"
    - os: linux
      dist: trusty
      env:
          N=BASE
          LAST_CMD=true
#    - os: osx
#      env:
#          N=OSX

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcode-select --install;true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install argp-standalone; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install valgrind; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libxml2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cunit; fi
  - pip install --user cpp-coveralls

addons:
  apt:
    packages:
    - cmake
    - time
    - valgrind
    - libcunit1-ncurses-dev
    - libxml2-utils
    - libc6-dev
    - gcc
    - g++
    - lcov

language: cpp

#compiler: clang

script: cmake . -DUNITTEST=ON $CMAKE_ARG && make && $LAST_CMD

after_success:
  - if [[ "$N" == "GCOV" ]];then ~/.local/bin/coveralls --exclude tests --gcov-options '\-lp';fi
